<Project>
    <!-- Sets target framework and language version -->
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>
    <!-- Sets build properties -->
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <AssemblyName>Venus</AssemblyName>
        <RootNamespace>Venus</RootNamespace>
    </PropertyGroup>
    <!-- Sets compilation options -->
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <!-- Sets global usings -->
    <ItemGroup>
        <Using Include="System" />
    </ItemGroup>
    <!-- Sets NuGet package dependencies -->
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-rc.1.26425.128" />
        <!-- Annotations -->
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
        <!-- Graphics -->
        <PackageReference Include="Silk.NET.WebGPU" Version="2.23.0" />
        <!-- Common -->
        <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
        <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
    </ItemGroup>
</Project>