<Project>
    <!-- Sets target framework and language version -->
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>
    <!-- Sets build properties -->
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <AssemblyName>Venus</AssemblyName>
        <RootNamespace>Venus</RootNamespace>
    </PropertyGroup>
    <!-- Sets compilation options -->
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <!-- Sets global usings -->
    <ItemGroup>
        <Using Include="System" />
        <Using Include="Microsoft.Xna.Framework" />
        <Using Include="Microsoft.Xna.Framework.Graphics" />
    </ItemGroup>
    <!-- Sets project dependencies -->
    <ItemGroup>
        <ProjectReference Include="..\..\submodules\FNA\FNA.Core.csproj" />
    </ItemGroup>
    <!-- Sets NuGet package dependencies -->
    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    </ItemGroup>
</Project>